name: Enterprise CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  security-and-lint:
    name: Lint & Vulnerability Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Lint Shell Scripts
        uses: ludeeus/action-shellcheck@master
        with:
          scandir: './scripts'

      - name: Validate docker-compose syntax
        run: docker-compose config -q

      - name: Run Trivy Vulnerability Scanner (IaC)
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'config'
          hide-progress: false
          format: 'table'
          exit-code: '0'
          ignore-unfixed: true
